### ISSUE TITLE
hey frosty it stopped work when inject th server need help

### ISSUE THREAD

**Issue by nongnoobjung** [frostycpu/FinalesFunkeln#7]
hey frosty it stopped work when inject th server need help

**Comment by frostycpu** [comment]
What exactly happens?

**Comment by nongnoobjung** [comment]
don't know what happen haha it not respond after inject

**Comment by frostycpu** [comment]
There should be an Error.log file, can you post its contents?

**Comment by yokrysty** [comment]
imediatly after I login into the LoL Client Finales Funkeln will crash with this error:
[7/18/2016 10:58:56 PM]
System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at RtmpSharp.Net.RtmpProxy.OnConnectMessageReceived(Object sender, ConnectMessageEventArgs e)
   at RtmpSharp.Net.RtmpProxySource.<EventReceivedCallback>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by frostycpu** [comment]
@yokrysty What server are you playing on?

**Comment by yokrysty** [comment]
EUNE

**Comment by frostycpu** [comment]
I'm not able to reproduce that error but I guess it's an ssl related issue. Are you running FF as  administrator?

**Comment by yokrysty** [comment]
yes i run it as admin, It's a strange crash, is happening only with some accounts.
I will run it in debugger and post here if I found the problem.
